# Inleiding

Technologie en automatisering heeft het werk van mensen sterk beïnvloed. De verwachting is dat dit niet minder zal worden, eerder meer. Machines nemen delen van het menselijk werk over en zorgen ervoor dat mensen weer andere taken kunnen uitvoeren. Machines lijken volwassen te worden en kunnen zaken uitvoeren die voorheen alleen door mensen konden worden uitgevoerd. In Japan wordt al 90% van het gewas met drones bespoten, Amazon werkt al met 100.000 robots, 80% van het werk in de auto-industrie wordt met robots uitgevoerd en in Engeland is er al een bedrijf dat er vanuit gaat in de nabije toekomst huizen te kunnen bouwen zonder mensen op de bouwplaats (Susskind, 2019). Ook binnen ons eigen onderzoekswerk verandert en zal nog steeds meer veranderen. 

Dat technologie en automatisering ons onderzoekswerk beïnvloedt is natuurlijk al het geval nu databestanden kunnen worden ingelezen, er van informatie kan worden geleerd, computers steeds maar sterker worden en met kunstmatige intelligentie betere keuzes kunnen worden gemaakt. Een invalshoek kiezen, een literatuursearch doen, de resultaten samenvatten, een bericht samenstellen, dat alles behoort tot de zeer nabije mogelijkheden. De technologische mogelijkheden helpen ons bij het verzamelen van informatie, het graven in databestanden, het genereren van invalshoeken, feiten verzamelen, het produceren van inhoud, het verifiëren en falsifiëren van informatie, het verspreiden en communiceren van informatie en ook het ontmaskeren van net nieuws. Technologie en automatisering gaat niet langs ons heen en data science loopt in deze ontwikkeling voorop. We zien dat op ons terrein hybride vormen ontstaan waarbij menselijke en kunstmatige intelligentie worden gekoppeld. 

Tegelijkertijd stellen we vast dat onderzoekers vaak niet zijn voorbereid op het benutten van deze technologieën, ze missen kennis en slagen er niet in op in te spelen op deze nieuwe innovaties. Als onderzoekers staan we regelmatig voor nieuwe uitdagingen en moeten we antwoord geven op nieuwe vragen. Dit raakt onze analytische vaardigheden en de manier waarop we omgaan met deze vragen. Hoe stellen we hypothesen, hoe verzamelen we data en brengen deze samen, hoe transformeren we dit naar hanteerbare informatie, hoe analyseren en visualiseren we dit en, tot slot, communiceren we dit. Het gaat hier om de manier waarop we met informatie omgaan, leren denken met informatie en hoe we daarbij de computer en de onderliggende programma’s gebruiken. Het is goed om de vaardigheid om te werken met informatie verder ontwikkelen en daarbij nieuwe technologieën kunnen gebruiken. Het is goed om als instituut over die toekomst na te denken. Dit alles in de wetenschap dat je nooit alles tegelijk kunt doen, dit stap voor stap moet ontwikkelen, je hier de tijd voor behoort te nemen en hier met elkaar aan werkt. 

Een eerste stap zou kunnen zijn om in kaart te brengen welke verschillende statistische programma’s er op dit moment voor handen zijn en te bekijken wel mogelijkheden zij bieden voor de nabije toekomst. We willen weten hoe deze programma’s verschillen en wat hun sterke en zwakke punten zijn. De beslissing welk programma (of programma’s) het beste bij zo’n nabije toekomst past, moet zorgvuldig worden genomen. Als je overstapt naar een nieuw systeem, kan dat leiden tot hoge kosten qua licenties en de nodige eisen stellen aan omscholing. Laten we de belangrijkste statistische programma’s eens op rij zetten en dat zijn op dit moment SPSS, STATA, SAS, R en Python en de voors en tegens op een rij zetten. We vergelijken voor elk van de programma’s de statistische methoden en mogelijkheden, de verklarende en voorspellende mogelijkheden, de toegankelijkheid en eenvoud, en de presentatiemogelijkheden. We zetten voor elk van die programma’s ook de sterke en zwakke punten op rij, we vertellen iets over de licentie en kosten en sluit af met enkele conclusies voor dat programma. Wanneer we dat hebben gedaan zullen we ook wat zeggen over big data en het omgaan daarmee. Tot slot hebben we een beperkt aantal medewerkers die op dit terrein interesse hebben enkele vragen voorgelegd. Tot slot sluiten we af met enkele conclusies. Dit stuk wil helpen wanneer er over deze toekomst wordt nagedacht.


